import { SITE, FORMATTED_ADDRESS } from "./site";

/**
 * Legal pages.
 *
 * Transcribed from wizardcomm.net. Two obvious template artefacts in the
 * source are corrected rather than republished — see the notes on the
 * definitions below — because a policy is the one page where a wrong fact is
 * a liability rather than a typo.
 */

export type LegalBlock =
  | { type: "text"; body: string }
  | { type: "list"; items: readonly string[] }
  | { type: "definitions"; items: readonly { term: string; body: string }[] };

export type LegalSection = {
  /** Anchor target, and the key the contents rail links to. */
  id: string;
  heading: string;
  blocks: readonly LegalBlock[];
};

export const PRIVACY_POLICY = {
  eyebrow: "Legal",
  title: "Privacy Policy",
  updated: "1 April 2025",
  lead: `Your privacy is very important to ${SITE.legalName}. You should be aware of how we handle any personal data you give us when using our service.`,

  sections: [
    {
      id: "definitions",
      heading: "Interpretation and definitions",
      blocks: [
        {
          type: "text",
          body: "Words whose initial letter is capitalised have meanings defined under the following conditions. These definitions have the same meaning whether they appear in singular or in plural.",
        },
        {
          type: "definitions",
          items: [
            {
              term: "Account",
              body: "A unique account created for You to access our Service or parts of our Service.",
            },
            {
              term: "Affiliate",
              body: "An entity that controls, is controlled by, or is under common control with a party.",
            },
            {
              term: "Application",
              body: "The software program provided by the Company.",
            },
            {
              term: "Company",
              body: `${SITE.legalName}, ${FORMATTED_ADDRESS}. Referred to as "the Company", "We", "Us" or "Our" in this agreement.`,
            },
            { term: "Country", body: "India." },
            {
              term: "Device",
              body: "Any device that can access the Service, such as a computer, a mobile phone or a tablet.",
            },
            {
              term: "Personal Data",
              body: "Any information that relates to an identified or identifiable individual.",
            },
            { term: "Service", body: "Refers to the Application." },
            {
              term: "Service Provider",
              body: "Any natural or legal person who processes data on behalf of the Company — third-party companies or individuals employed to facilitate the Service, provide it on our behalf, perform services related to it, or assist us in analysing how it is used.",
            },
            {
              term: "Third-party Social Media Service",
              body: "Any website or social network through which a User can log in or create an account to use the Service.",
            },
            {
              term: "Usage Data",
              body: "Data collected automatically, either generated by use of the Service or from the Service infrastructure itself.",
            },
            {
              term: "You",
              body: "The individual accessing or using the Service, or the company or other legal entity on behalf of which that individual is doing so.",
            },
          ],
        },
      ],
    },
    {
      id: "data-we-collect",
      heading: "Collecting and using your personal data",
      blocks: [
        {
          type: "text",
          body: "While using our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include Your email address, name, phone number, address details and usage data.",
        },
        {
          type: "text",
          body: "Usage Data is collected automatically. It may include Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
        },
        {
          type: "text",
          body: "The Company allows You to create an account and log in through Google, Facebook, Instagram, Twitter and LinkedIn. If You decide to do so, We may collect Personal Data that is already associated with Your Third-Party Social Media Service's account, such as Your name, Your email address, Your activities or Your contact list associated with that account.",
        },
        {
          type: "text",
          body: "While using Our Application, and with Your prior permission, We may collect information regarding Your location, Your device's contacts, pictures, and other information from Your camera and photo library.",
        },
      ],
    },
    {
      id: "how-we-use-it",
      heading: "Use of your personal data",
      blocks: [
        { type: "text", body: "The Company may use Personal Data for the following purposes:" },
        {
          type: "list",
          items: [
            "To provide and maintain our Service, including monitoring its usage.",
            "To manage Your account and Your registration as a user of the Service.",
            "To perform a contract for the products or services You have purchased.",
            "To contact You regarding updates and security information.",
            "To provide You with news, special offers and general information about similar goods and services.",
            "To manage Your requests to Us.",
            "To facilitate business transfers during a merger or sale of assets.",
            "For data analysis, identifying usage trends and improving the Service.",
          ],
        },
      ],
    },
    {
      id: "sharing",
      heading: "Sharing your personal information",
      blocks: [
        { type: "text", body: "We may share Your personal information in the following situations:" },
        {
          type: "list",
          items: [
            "With Service Providers, to monitor and analyse the use of our Service and to contact You.",
            "For business transfers involving a merger or a sale of assets.",
            "With Affiliates, who are required to honour this Privacy Policy.",
            "With business partners, to offer You certain products, services or promotions.",
            "With other users, where You interact in public areas or through a Third-Party Social Media Service.",
            "With Your consent, for any other purpose.",
          ],
        },
      ],
    },
    {
      id: "retention",
      heading: "Retention of your personal data",
      blocks: [
        {
          type: "text",
          body: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes and enforce our legal agreements and policies.",
        },
        {
          type: "text",
          body: "Usage Data is generally retained for a shorter period, except where it is used to strengthen security or improve the functionality of Our Service, or where We are legally obligated to retain it for longer.",
        },
      ],
    },
    {
      id: "transfer",
      heading: "Transfer of your personal data",
      blocks: [
        {
          type: "text",
          body: "Your information, including Personal Data, may be processed and transferred to computers located outside of Your state, province, country or other governmental jurisdiction, where the data protection laws may differ from those of Your jurisdiction.",
        },
        {
          type: "text",
          body: "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy, and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
        },
      ],
    },
    {
      id: "deletion",
      heading: "Delete your personal data",
      blocks: [
        {
          type: "text",
          body: "You have the right to delete, or to request that We assist in deleting, the Personal Data that We have collected about You. You may update, amend or delete Your information at any time by signing in to Your account and visiting the account settings section, or by contacting Us.",
        },
        {
          type: "text",
          body: "Please note that We may need to retain certain information when We have a legal obligation or lawful basis to do so.",
        },
      ],
    },
    {
      id: "disclosure",
      heading: "Disclosure of your personal data",
      blocks: [
        {
          type: "text",
          body: "If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
        },
        {
          type: "text",
          body: "The Company may be required to disclose Your Personal Data if required to do so by law, or in response to valid requests by public authorities such as a court or a government agency.",
        },
        {
          type: "text",
          body: "The Company may also disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate possible wrongdoing in connection with the Service, protect the personal safety of Users of the Service or the public, or protect against legal liability.",
        },
      ],
    },
    {
      id: "security",
      heading: "Security of your personal data",
      blocks: [
        {
          type: "text",
          body: "Industry-standard security measures are in place on our websites and Services to guard against the loss, misuse, access, modification, disclosure and destruction of the data that is in our control. Sensitive data is encrypted using Secure Socket Layer (SSL).",
        },
        {
          type: "text",
          body: "No method of transmission over the Internet, or method of electronic storage, is perfectly secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security, and You remain responsible for Your own transmissions to Us. We do not sell personal information to third parties unless specifically stated.",
        },
      ],
    },
    {
      id: "age",
      heading: "Age of consent",
      blocks: [
        {
          type: "text",
          body: "By using this Service, You represent that You are at least the age of majority in Your state or province of residence, or that You are the age of majority and have given Us Your consent to allow any of Your minor dependents to use this Service.",
        },
      ],
    },
    {
      id: "cookies",
      heading: "Cookies",
      blocks: [
        {
          type: "text",
          body: "When appropriate and required, we use cookies or comparable technologies to automatically gather data from your browser, IP address or device for the purposes of validating your license, processing payments and other measurement needs.",
        },
      ],
    },
    {
      id: "third-party-links",
      heading: "Links to other websites",
      blocks: [
        {
          type: "text",
          body: "Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over, and assume no responsibility for, the content, privacy policies or practices of any third-party sites or services.",
        },
      ],
    },
    {
      id: "changes",
      heading: "Changes to this privacy policy",
      blocks: [
        {
          type: "text",
          body: "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the date at the top of it. Changes are effective when they are posted on this page.",
        },
      ],
    },
    {
      id: "contact",
      heading: "Contact us",
      blocks: [
        {
          type: "text",
          body: "If you have any questions about this Privacy Policy, you can reach us at the details below.",
        },
      ],
    },
  ] satisfies readonly LegalSection[],
} as const;

/**
 * Accessibility statement.
 *
 * Written from what this site actually does, not from a template: every claim
 * below is checkable in the codebase, and the limitations are stated rather
 * than omitted. An accessibility statement that overclaims is worse than none,
 * because it tells a disabled user the barrier they just hit should not exist.
 */
export const ACCESSIBILITY = {
  eyebrow: "Legal",
  title: "Accessibility",
  updated: "11 August 2026",
  lead: `${SITE.legalName} aims to make this website usable by as many people as possible, including those who browse with a keyboard, a screen reader, magnification, or reduced motion enabled.`,

  sections: [
    {
      id: "standard",
      heading: "The standard we aim for",
      blocks: [
        {
          type: "text",
          body: "We target WCAG 2.1 Level AA. That is the level most commonly referenced in procurement and in accessibility law, and it is the level this site was designed and built against rather than retrofitted to.",
        },
        {
          type: "text",
          body: "We have not commissioned an independent audit. The statement below describes what we have implemented and verified ourselves.",
        },
      ],
    },
    {
      id: "measures",
      heading: "What we have done",
      blocks: [
        {
          type: "list",
          items: [
            "Colour contrast is measured rather than estimated. Every body-size text and background pair in both the light and dark themes was checked in-browser, and one colour was lightened after it fell short at 4.1:1.",
            "Both themes are designed, not inverted. The site follows your operating system preference by default and can be switched manually.",
            "A skip link is the first thing in the tab order on every page, so keyboard users can bypass the header and navigation.",
            "Every interactive element has a visible focus outline, offset from the element so it stays legible against any background.",
            "Motion respects prefers-reduced-motion throughout. Animated content renders in its final state rather than being hidden, so nothing is reachable only through movement.",
            "Carousels that play automatically expose a pause control, as WCAG 2.2.2 requires of motion running longer than five seconds.",
            "Menus, accordions, dialogs and drawers are built on accessible primitives that manage focus, trap it while open, restore it on close, and support arrow-key navigation.",
            "Forms label every field, mark errors with aria-invalid and aria-describedby rather than colour alone, and announce results in a live region without moving focus.",
            "Images that carry meaning have descriptive alternative text. Decorative images are marked as such so screen readers skip them instead of announcing filenames.",
            "Headings follow a single hierarchy per page, with exactly one first-level heading.",
            "The site is built as static HTML with progressive enhancement, so content and forms work before JavaScript loads.",
          ],
        },
      ],
    },
    {
      id: "limitations",
      heading: "Known limitations",
      blocks: [
        {
          type: "text",
          body: "We would rather name these than let you discover them:",
        },
        {
          type: "list",
          items: [
            "The map on our contact page is an embedded Google Maps frame. Its interface is Google's and outside our control; the same address is printed as text beside it, so no information is only available inside the map.",
            "Some client and partner logos are supplied as images with text baked into them. Where that happens the organisation's name also appears as real text nearby.",
            "A few case-study images published by clients include text within the artwork. The same information appears in the page copy.",
            "We have not tested with every combination of assistive technology and browser. If something does not work with yours, please tell us.",
          ],
        },
      ],
    },
    {
      id: "feedback",
      heading: "Tell us if something does not work",
      blocks: [
        {
          type: "text",
          body: "If you meet a barrier on this site, or need something here in a different format, email us and we will put it right. Please include the page address and what you were trying to do — that is usually enough for us to reproduce it.",
        },
        {
          type: "text",
          body: "We aim to respond within one working day.",
        },
      ],
    },
  ] satisfies readonly LegalSection[],
} as const;
